server:
  environment: development
  port: 8000

database:
  # Connect to local MySQL instance from Docker container
  url: mysql+pymysql://mikko:StrongPass123!@host.docker.internal:3306/mikkoBlog

cors:
  allow_origins:
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
    - "http://localhost:3000"
    - "*"

jwt:
  secret: "please_change_me_in_env"
  algorithm: "HS256"
  expires_minutes: 1440

admin:
  email: "admin@example.com"
  password: "admin123"



