server:
  environment: production
  port: 8000

database:
  # Docker环境中的数据库连接
  url: mysql+pymysql://mikko:mikko_pass@db:3306/mikkoBlog

cors:
  allow_origins:
    - "http://localhost"
    - "http://localhost:80"
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://127.0.0.1"
    - "http://127.0.0.1:80"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:5173"

jwt:
  secret: "your_super_secret_jwt_key_change_this_in_production"
  algorithm: "HS256"
  expires_minutes: 1440

admin:
  email: "admin@example.com"
  password: "admin123"

image_search:
  # Unsplash API密钥 (可选，不填写将使用备用图片源)
  # 获取地址: https://unsplash.com/developers
  unsplash_access_key: "demo_key"
