server:
  environment: development
  port: 8000

database:
  # Connect to local MySQL instance from Docker container
  url: mysql+pymysql://mikko:StrongPass123!@localhost:3306/mikkoBlog

cors:
  allow_origins:
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
    - "http://localhost:3000"
    - "*"

jwt:
  secret: "please_change_me_in_env"
  algorithm: "HS256"
  expires_minutes: 1440

admin:
  email: "admin@example.com"
  password: "admin123"

image_search:
  # Unsplash API密钥 (可选，不填写将使用备用图片源)
  # 获取地址: https://unsplash.com/developers
  unsplash_access_key: "demo_key"
